package(default_visibility = ["//visibility:public"])

cc_library(
    name = "llminfer_graph",
    srcs = glob([
        "LLMInfer/graph/**/*.cpp",
    ]),
    hdrs = glob([
        "LLMInfer/graph/**/*.h",
    ]),
    copts = ["-std=c++17"],
    includes = ["LLMInfer"],
)

cc_library(
    name = "llminfer_stream",
    srcs = ["LLMInfer/stream/stream.cpp"],
    hdrs = ["LLMInfer/stream/stream.h"],
    copts = ["-std=c++17"],
    includes = ["LLMInfer"],
)

cc_library(
    name = "llminfer_kernel",
    srcs = [
        "LLMInfer/kernel/cuda_kernel_jit_builder.cpp",
        "LLMInfer/kernel/kernel_factory.cpp",
    ],
    hdrs = glob(["LLMInfer/kernel/*.h"]),
    copts = ["-std=c++17"],
    includes = ["LLMInfer"],
)

cc_library(
    name = "llminfer_test_utils",
    hdrs = ["test/llminfer/test_utils.h"],
    includes = ["."],
)

cc_test(
    name = "graph_aspect_test",
    srcs = ["test/llminfer/graph_aspect_test.cpp"],
    deps = [
        ":llminfer_graph",
        ":llminfer_test_utils",
    ],
)

cc_test(
    name = "graph_element_test",
    srcs = ["test/llminfer/graph_element_test.cpp"],
    deps = [
        ":llminfer_graph",
        ":llminfer_test_utils",
    ],
)

cc_test(
    name = "graph_group_node_optimizer_test",
    srcs = ["test/llminfer/graph_group_node_optimizer_test.cpp"],
    deps = [
        ":llminfer_graph",
        ":llminfer_test_utils",
    ],
)

cc_test(
    name = "graph_param_pipeline_test",
    srcs = ["test/llminfer/graph_param_pipeline_test.cpp"],
    deps = [
        ":llminfer_graph",
        ":llminfer_test_utils",
    ],
)

cc_test(
    name = "graph_integration_test",
    srcs = ["test/llminfer/graph_integration_test.cpp"],
    deps = [
        ":llminfer_graph",
        ":llminfer_test_utils",
    ],
)

cc_test(
    name = "stream_test",
    srcs = ["test/llminfer/stream_test.cpp"],
    deps = [
        ":llminfer_stream",
        ":llminfer_test_utils",
    ],
)

cc_test(
    name = "kernel_test",
    srcs = ["test/llminfer/kernel_test.cpp"],
    deps = [
        ":llminfer_kernel",
        ":llminfer_test_utils",
    ],
)